start_urls:
    - https://www.virgio.com/
    - https://www.tatacliq.com/
    - https://nykaafashion.com/
    - https://www.westside.com/

patterns:
  - products
  - items
  - p
  - ^p-.*

semaphore_limit: 20

# patterns-
#   - https://www.virgio.com/    -    /products/
#   - https://www.tatacliq.com/  -    /p-
#   - https://nykaafashion.com/  -    /p/
#   - https://www.westside.com/  -    /products/