start_urls:
    - https://www.virgio.com/
    - https://www.tatacliq.com/
    - https://nykaafashion.com/
    - https://www.westside.com/

patterns:
  - products
  - items
  - p
  - ^p-.*

semaphore_limit: 20

# patterns-
#   - https://www.virgio.com/    -    /products/
#   - https://www.tatacliq.com/  -    /p- (product urls are being loaded by javascript)
#   - https://nykaafashion.com/  -    /p/ (giving 403 forbidden error, high security is implemented)
#   - https://www.westside.com/  -    /products/